package javabuckets.mods.rcm.skills.herblore;

import javabuckets.mods.rcm.items.herblore.ItemEmptyVial;
import javabuckets.mods.rcm.items.herblore.ItemHerbloreItem;
import javabuckets.mods.rcm.items.herblore.ItemRSPotion;
import javabuckets.mods.rcm.utility.ItemRegistry;
import net.minecraft.item.Item;

public class ModHerbloreItems 
{
	public static Item pestle_mortar;
	public static Item vial;
	public static Item vial_water;
	
	public static Item cleanGuam;
	public static Item cleanTarromin;
	public static Item cleanMarrentill;
	public static Item cleanHarralander;
	public static Item cleanRanarr;
	public static Item cleanToadflax;
	public static Item cleanSpiritWeed;
	public static Item cleanIrit;
	public static Item cleanWergali;
	public static Item cleanAvantoe;
	public static Item cleanKwuarm;
	public static Item cleanSnapdragon;
	public static Item cleanCadantine;
	public static Item cleanLantadyme;
	public static Item cleanDwarfWeed;
	public static Item cleanTorstol;
	public static Item cleanFellstalk;
	
	public static Item potion_attack;
	public static Item potion_ranging;
	public static Item potion_magic;
	public static Item potion_strength;
	public static Item potion_defence;
	public static Item potion_antipoison;
	public static Item potion_guthixRest;
	public static Item potion_statRestore;
	public static Item potion_energy;
	public static Item potion_agility;
	public static Item potion_prayer;
	public static Item potion_summoning;
	public static Item potion_crafting;
	public static Item potion_fishing;
	public static Item potion_hunter;
	public static Item potion_fletching;
	public static Item potion_antifire;
	public static Item potion_zamorakBrew;
	public static Item potion_saradominBrew;
	public static Item potion_adrenaline;
	
	public static Item superpotion_attack;
	public static Item superpotion_antipoison;
	public static Item superpotion_energy;
	public static Item superpotion_strength;
	public static Item superpotion_statRestore;
	public static Item superpotion_defence;
	public static Item superpotion_ranging;
	public static Item superpotion_magic;
	public static Item superpotion_antifire;
	public static Item superpotion_saradominBrew;
	public static Item superpotion_zamorakBrew;
	public static Item superpotion_guthixRest;
	public static Item superpotion_prayer;
	
	public static Item extremepotion_attack;
	public static Item extremepotion_strength;
	public static Item extremepotion_defence;
	public static Item extremepotion_magic;
	public static Item extremepotion_ranging;
	public static Item extremepotion_overload;
	
	public static Item eye_of_newt;
	public static Item limpwurt;
	public static Item dust_unicorn_horn;
	public static Item dust_chocolate;
	public static Item snape_grass;
	public static Item dust_dragon_scale;
	public static Item crushed_nest;
	
	public static void init()
	{
		pestle_mortar = new ItemHerbloreItem("pestle_and_mortar");
		ItemRegistry.registerItem(pestle_mortar, true);

		vial = new ItemEmptyVial("vial");
		ItemRegistry.registerItem(vial, false);
		vial_water = new ItemHerbloreItem("vial_of_water");
		ItemRegistry.registerItem(vial_water, false);
		
		cleanGuam = new ItemHerbloreItem("clean_guam");
		ItemRegistry.registerItem(cleanGuam, false);
		cleanTarromin = new ItemHerbloreItem("clean_tarromin");
		ItemRegistry.registerItem(cleanTarromin, false);
		cleanMarrentill = new ItemHerbloreItem("clean_marrentill");
		ItemRegistry.registerItem(cleanMarrentill, false);
		cleanHarralander = new ItemHerbloreItem("clean_harralander");
		ItemRegistry.registerItem(cleanHarralander, false);
		cleanRanarr = new ItemHerbloreItem("clean_ranarr");
		ItemRegistry.registerItem(cleanRanarr, false);
		cleanToadflax = new ItemHerbloreItem("clean_toadflax");
		ItemRegistry.registerItem(cleanToadflax, false);
		cleanSpiritWeed = new ItemHerbloreItem("clean_spirit_weed");
		ItemRegistry.registerItem(cleanSpiritWeed, false);
		cleanIrit = new ItemHerbloreItem("clean_irit");
		ItemRegistry.registerItem(cleanIrit, false);
		cleanWergali = new ItemHerbloreItem("clean_wergali");
		ItemRegistry.registerItem(cleanWergali, false);
		cleanAvantoe = new ItemHerbloreItem("clean_avantoe");
		ItemRegistry.registerItem(cleanAvantoe, false);
		cleanKwuarm = new ItemHerbloreItem("clean_kwuarm");
		ItemRegistry.registerItem(cleanKwuarm, false);
		cleanSnapdragon = new ItemHerbloreItem("clean_snapdragon");
		ItemRegistry.registerItem(cleanSnapdragon, false);
		cleanCadantine = new ItemHerbloreItem("clean_cadantine");
		ItemRegistry.registerItem(cleanCadantine, false);
		cleanLantadyme = new ItemHerbloreItem("clean_lantadyme");
		ItemRegistry.registerItem(cleanLantadyme, false);
		cleanDwarfWeed = new ItemHerbloreItem("clean_dwarf_weed");
		ItemRegistry.registerItem(cleanDwarfWeed, false);
		cleanTorstol = new ItemHerbloreItem("clean_torstol");
		ItemRegistry.registerItem(cleanTorstol, false);
		cleanFellstalk = new ItemHerbloreItem("clean_fellstalk");
		ItemRegistry.registerItem(cleanFellstalk, false);
		
		potion_attack = new ItemRSPotion("potion_attack");
		ItemRegistry.registerItem(potion_attack, false);
		potion_ranging = new ItemRSPotion("potion_ranged");
		ItemRegistry.registerItem(potion_ranging, false);
		potion_magic = new ItemRSPotion("potion_magic");
		ItemRegistry.registerItem(potion_magic, false);
		potion_strength = new ItemRSPotion("potion_strength");
		ItemRegistry.registerItem(potion_strength, false);
		potion_defence = new ItemRSPotion("potion_defence");
		ItemRegistry.registerItem(potion_defence, false);
		potion_antipoison = new ItemRSPotion("potion_antipoison");
		ItemRegistry.registerItem(potion_antipoison, false);
		potion_guthixRest = new ItemRSPotion("potion_guthix_rest");
		ItemRegistry.registerItem(potion_guthixRest, false);
		potion_statRestore = new ItemRSPotion("potion_restore");
		ItemRegistry.registerItem(potion_statRestore, false);
		potion_energy = new ItemRSPotion("potion_energy");
		ItemRegistry.registerItem(potion_energy, false);
		potion_agility = new ItemRSPotion("potion_agility");
		ItemRegistry.registerItem(potion_agility, false);
		potion_prayer = new ItemRSPotion("potion_prayer");
		ItemRegistry.registerItem(potion_prayer, false);
		potion_summoning = new ItemRSPotion("potion_summoning");
		ItemRegistry.registerItem(potion_summoning, false);
		potion_crafting = new ItemRSPotion("potion_crafting");
		ItemRegistry.registerItem(potion_crafting, false);
		potion_fishing = new ItemRSPotion("potion_fishing");
		ItemRegistry.registerItem(potion_fishing, false);
		potion_hunter = new ItemRSPotion("potion_hunter");
		ItemRegistry.registerItem(potion_hunter, false);
		potion_fletching = new ItemRSPotion("potion_fletching");
		ItemRegistry.registerItem(potion_fletching, false);
		potion_antifire = new ItemRSPotion("potion_antifire");
		ItemRegistry.registerItem(potion_antifire, false);
		potion_zamorakBrew = new ItemRSPotion("potion_zamorak_brew");
		ItemRegistry.registerItem(potion_zamorakBrew, false);
		potion_saradominBrew = new ItemRSPotion("potion_saradomin_brew");
		ItemRegistry.registerItem(potion_saradominBrew, false);
		potion_adrenaline = new ItemRSPotion("potion_adrenaline");
		ItemRegistry.registerItem(potion_adrenaline, false);
		
		superpotion_attack = new ItemRSPotion("potion_super_attack");
		ItemRegistry.registerItem(superpotion_attack, false);
		superpotion_antipoison = new ItemRSPotion("potion_super_antipoison");
		ItemRegistry.registerItem(superpotion_antipoison, false);
		superpotion_energy = new ItemRSPotion("potion_super_energy");
		ItemRegistry.registerItem(superpotion_energy, false);
		superpotion_strength = new ItemRSPotion("potion_super_strength");
		ItemRegistry.registerItem(superpotion_strength, false);
		superpotion_statRestore = new ItemRSPotion("potion_super_restore");
		ItemRegistry.registerItem(superpotion_statRestore, false);
		superpotion_defence = new ItemRSPotion("potion_super_defence");
		ItemRegistry.registerItem(superpotion_defence, false);
		superpotion_ranging = new ItemRSPotion("potion_super_ranged");
		ItemRegistry.registerItem(superpotion_ranging, false);
		superpotion_magic = new ItemRSPotion("potion_super_magic");
		ItemRegistry.registerItem(superpotion_magic, false);
		superpotion_antifire = new ItemRSPotion("potion_super_antifire");
		ItemRegistry.registerItem(superpotion_antifire, false);
		superpotion_saradominBrew = new ItemRSPotion("potion_super_saradomin_brew");
		ItemRegistry.registerItem(superpotion_saradominBrew, false);
		superpotion_zamorakBrew = new ItemRSPotion("potion_super_zamorak_brew");
		ItemRegistry.registerItem(superpotion_zamorakBrew, false);
		superpotion_guthixRest = new ItemRSPotion("potion_super_guthix_rest");
		ItemRegistry.registerItem(superpotion_guthixRest, false);
		superpotion_prayer = new ItemRSPotion("potion_super_prayer");
		ItemRegistry.registerItem(superpotion_prayer, false);
		
		extremepotion_attack = new ItemRSPotion("potion_extreme_attack");
		ItemRegistry.registerItem(extremepotion_attack, false);
		extremepotion_strength = new ItemRSPotion("potion_extreme_strength");
		ItemRegistry.registerItem(extremepotion_strength, false);
		extremepotion_defence = new ItemRSPotion("potion_extreme_defence");
		ItemRegistry.registerItem(extremepotion_defence, false);
		extremepotion_magic = new ItemRSPotion("potion_extreme_magic");
		ItemRegistry.registerItem(extremepotion_magic, false);
		extremepotion_ranging = new ItemRSPotion("potion_extreme_ranged");
		ItemRegistry.registerItem(extremepotion_ranging, false);
		extremepotion_overload = new ItemRSPotion("potion_overload");
		ItemRegistry.registerItem(extremepotion_overload, false);
		
		eye_of_newt = new ItemHerbloreItem("eye_of_newt");
		ItemRegistry.registerItem(eye_of_newt, false);
		limpwurt = new ItemHerbloreItem("limpwurt");
		ItemRegistry.registerItem(limpwurt, false);
		dust_unicorn_horn = new ItemHerbloreItem("unicorn_horn_dust");
		ItemRegistry.registerItem(dust_unicorn_horn, false);
		dust_chocolate = new ItemHerbloreItem("chocolate_dust");
		ItemRegistry.registerItem(dust_chocolate, false);
		snape_grass = new ItemHerbloreItem("snape_grass");
		ItemRegistry.registerItem(snape_grass, false);
		dust_dragon_scale = new ItemHerbloreItem("dragon_scale_dust");
		ItemRegistry.registerItem(dust_dragon_scale, false);
		crushed_nest = new ItemHerbloreItem("crushed_nest");
		ItemRegistry.registerItem(crushed_nest, false);
	}
}