package javabuckets.mods.rcm.skills.magic;

public class MagicReference 
{
	public static boolean isUsingAirStrike;
	public static boolean isUsingConfuse;
	public static boolean isUsingWaterStrike;
	public static boolean isUsingEarthStrike;
	public static boolean isUsingWeaken;
	public static boolean isUsingFireStrike;
	public static boolean isUsingAirBolt;
	public static boolean isUsingCurse;
	public static boolean isUsingBind;
	public static boolean isUsingWaterBolt;
	public static boolean isUsingEarthBolt;
	public static boolean isUsingFireBolt;
	public static boolean isUsingAirBlast;
	public static boolean isUsingWaterBlast;
	public static boolean isUsingSnare;
	public static boolean isUsingSlayerDart;
	public static boolean isUsingEarthBlast;
	public static boolean isUsingFireBlast;
	public static boolean isUsingDivineStorm;
	public static boolean isUsingAirWave;
	public static boolean isUsingWaterWave;
	public static boolean isUsingVulnerability;
	public static boolean isUsingEarthWave;
	public static boolean isUsingEnfeeble;
	public static boolean isUsingFireWave;
	public static boolean isUsingStormOfArmadyl;
	public static boolean isUsingEntangle;
	public static boolean isUsingPolyporeStrike;
	public static boolean isUsingStagger;
	public static boolean isUsingAirSurge;
	public static boolean isUsingWaterSurge;
	public static boolean isUsingTeleportBlock;
	public static boolean isUsingEarthSurge;
	public static boolean isUsingFireSurge;
	
	public static String airStrike = "air_strike";
	public static String confuse = "confuse";
	public static String waterStrike = "water_strike";
	public static String earthStrike = "earth_strike";
	public static String weaken = "weaken";
	public static String fireStrike = "fire_strike";
	public static String airBolt = "air_bolt";
	public static String curse = "curse";
	public static String bind = "bind";
	public static String waterBolt = "water_bolt";
	public static String earthBolt = "earth_bolt";
	public static String fireBolt = "fire_bolt";
	public static String airBlast = "air_blast";
	public static String waterBlast = "water_blast";
	public static String snare = "snare";
	public static String slayerDart = "slayer_dart";
	public static String earthBlast = "earth_blast";
	public static String fireBlast = "fire_blast";
	public static String divineStorm = "divine_storm";
	public static String airWave = "air_wave";
	public static String waterWave = "water_wave";
	public static String vulnerability = "vulnerability";
	public static String earthWave = "earth_wave";
	public static String fireWave = "fire_wave";
	public static String stormOfArmadyl = "storm_of_armadyl";
	public static String entangle = "entangle";
	public static String polyporeStrike = "polypore_strike";
	public static String stagger = "stagger";
	public static String airSurge = "air_surge";
	public static String waterSurge = "water_surge";
	public static String teleBlock = "teleport_block";
	public static String earthSurge = "earth_surge";
	public static String fireSurge = "fire_surge";
}